### lets deploy RF model with hyper parameter tuning
it gave me a better validation accuracy 80%

In [1]:
import pandas as pd 
import numpy as np                     # For mathematical calculations 
import seaborn as sns                  # For data visualization 
import matplotlib.pyplot as plt        # For plotting graphs 
%matplotlib inline 
import warnings                        # To ignore any warnings
warnings.filterwarnings("ignore")

In [2]:
train=pd.read_csv("train_FE2.csv") 
test=pd.read_csv("test_FE2.csv")

In [3]:
train=train.drop('Loan_ID',axis=1) 
test=test.drop('Loan_ID',axis=1)

In [4]:
X = train.drop('Loan_Status',1) 
y = train.Loan_Status

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

In [7]:
i=1 
mean_validation_score=0
kf = StratifiedKFold(n_splits=5,random_state=1,shuffle=True) 
for train_index,test_index in kf.split(X,y): 
    print('n{} of kfold {}'.format(i,kf.n_splits)) 
    xtr,xvl = X.loc[train_index],X.loc[test_index] 
    ytr,yvl = y[train_index],y[test_index] 
    model = RandomForestClassifier(random_state=1, max_depth=7, n_estimators=61)     
    model.fit(xtr, ytr) 
    pred_test = model.predict(xvl) 
    score = accuracy_score(yvl,pred_test) 
    print('accuracy_score',score) 
    i+=1 
    mean_validation_score+=score
print("mean validation accuracy",mean_validation_score/5)

pred_test = model.predict(test) 
pred2 =  model.predict_proba(test)
#pred2     

n1 of kfold 5
accuracy_score 0.8211382113821138
n2 of kfold 5
accuracy_score 0.8455284552845529
n3 of kfold 5
accuracy_score 0.7886178861788617
n4 of kfold 5
accuracy_score 0.7886178861788617
n5 of kfold 5
accuracy_score 0.7786885245901639
mean validation accuracy 0.8045181927229107


## Pickling The Model file For Deployment

In [8]:
import pickle

In [12]:
pickle.dump(model,open('RFmodel.pkl',"wb"))

In [14]:
pickled_model=pickle.load(open('RFmodel.pkl','rb'))

In [23]:
## Prediction
pickled_model.predict(test.loc[7].values.reshape(1, -1))

array([0], dtype=int64)

In [26]:
pickled_model.predict(test.loc[0].values.reshape(1, -1))

array([1], dtype=int64)

In [20]:
test.loc[0].values

array([1.00000000e+00, 4.70048037e+00, 0.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 5.72000000e+03, 8.65172408e+00, 3.05555556e-01,
       5.41444444e+03])